# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ namTag.create!(name: "Star Wars".downcase) }, { namTag.create!(name: "Lord of the Rings".downcase) }])
#   Character.create(namTag.create!(name: "Luke".downcase), movie: movies.first)




puts 'seeding tags'

Tag.create!(name: 'top')
Tag.create!(name: 'mid')
Tag.create!(name: 'jungle')
Tag.create!(name: 'adc')
Tag.create!(name: 'support')

Tag.create!(name: 'teamfight')
Tag.create!(name: 'outplay')
Tag.create!(name: 'funny')
Tag.create!(name: 'gank')
Tag.create!(name: 'fed')

Tag.create!(name: '1vX')
Tag.create!(name: '1v1')

Tag.create!(name: 'bot')

Tag.create!(name: "AATROX".downcase)
Tag.create!(name: "AHRI".downcase)
Tag.create!(name: "AKALI".downcase)
Tag.create!(name: "AKSHAN".downcase)
Tag.create!(name: "ALISTAR".downcase)
Tag.create!(name: "AMUMU".downcase)
Tag.create!(name: "ANIVIA".downcase)
Tag.create!(name: "ANNIE".downcase)
Tag.create!(name: "APHELIOS".downcase)
Tag.create!(name: "ASHE".downcase)
Tag.create!(name: "AURELION SOL".downcase)
Tag.create!(name: "AZIR".downcase)
Tag.create!(name: "BARD".downcase)
Tag.create!(name: "BEL'VETH".downcase)
Tag.create!(name: "BLITZCRANK".downcase)
Tag.create!(name: "BRAND".downcase)
Tag.create!(name: "BRAUM".downcase)
Tag.create!(name: "CAITLYN".downcase)
Tag.create!(name: "CAMILLE".downcase)
Tag.create!(name: "CASSIOPEIA".downcase)
Tag.create!(name: "CHO'GATH".downcase)
Tag.create!(name: "CORKI".downcase)
Tag.create!(name: "DARIUS".downcase)
Tag.create!(name: "DIANA".downcase)
Tag.create!(name: "DR. MUNDO".downcase)
Tag.create!(name: "DRAVEN".downcase)
Tag.create!(name: "EKKO".downcase)
Tag.create!(name: "ELISE".downcase)
Tag.create!(name: "EVELYNN".downcase)
Tag.create!(name: "EZREAL".downcase)
Tag.create!(name: "FIDDLESTICKS".downcase)
Tag.create!(name: "FIORA".downcase)
Tag.create!(name: "FIZZ".downcase)
Tag.create!(name: "GALIO".downcase)
Tag.create!(name: "GANGPLANK".downcase)
Tag.create!(name: "GAREN".downcase)
Tag.create!(name: "GNAR".downcase)
Tag.create!(name: "GRAGAS".downcase)
Tag.create!(name: "GRAVES".downcase)
Tag.create!(name: "GWEN".downcase)
Tag.create!(name: "HECARIM".downcase)
Tag.create!(name: "HEIMERDINGER".downcase)
Tag.create!(name: "ILLAOI".downcase)
Tag.create!(name: "IRELIA".downcase)
Tag.create!(name: "IVERN".downcase)
Tag.create!(name: "JANNA".downcase)
Tag.create!(name: "JARVAN IV".downcase)
Tag.create!(name: "JAX".downcase)
Tag.create!(name: "JAYCE".downcase)
Tag.create!(name: "JHIN".downcase)
Tag.create!(name: "JINX".downcase)
Tag.create!(name: "KAI'SA".downcase)
Tag.create!(name: "KALISTA".downcase)
Tag.create!(name: "KARMA".downcase)
Tag.create!(name: "KARTHUS".downcase)
Tag.create!(name: "KASSADIN".downcase)
Tag.create!(name: "KATARINA".downcase)
Tag.create!(name: "KAYLE".downcase)
Tag.create!(name: "KAYN".downcase)
Tag.create!(name: "KENNEN".downcase)
Tag.create!(name: "KHA'ZIX".downcase)
Tag.create!(name: "KINDRED".downcase)
Tag.create!(name: "KLED".downcase)
Tag.create!(name: "KOG'MAW".downcase)
Tag.create!(name: "LEBLANC".downcase)
Tag.create!(name: "LEE SIN".downcase)
Tag.create!(name: "LEONA".downcase)
Tag.create!(name: "LILLIA".downcase)
Tag.create!(name: "LISSANDRA".downcase)
Tag.create!(name: "LUCIAN".downcase)
Tag.create!(name: "LULU".downcase)
Tag.create!(name: "LUX".downcase)
Tag.create!(name: "MALPHITE".downcase)
Tag.create!(name: "MALZAHAR".downcase)
Tag.create!(name: "MAOKAI".downcase)
Tag.create!(name: "MASTER YI".downcase)
Tag.create!(name: "MISS FORTUNE".downcase)
Tag.create!(name: "MORDEKAISER".downcase)
Tag.create!(name: "MORGANA".downcase)
Tag.create!(name: "NAMI".downcase)
Tag.create!(name: "NASUS".downcase)
Tag.create!(name: "NAUTILUS".downcase)
Tag.create!(name: "NEEKO".downcase)
Tag.create!(name: "NIDALEE".downcase)
Tag.create!(name: "NILAH".downcase)
Tag.create!(name: "NOCTURNE".downcase)
Tag.create!(name: "NUNU & WILLUMP".downcase)
Tag.create!(name: "OLAF".downcase)
Tag.create!(name: "ORIANNA".downcase)
Tag.create!(name: "ORNN".downcase)
Tag.create!(name: "PANTHEON".downcase)
Tag.create!(name: "POPPY".downcase)
Tag.create!(name: "PYKE".downcase)
Tag.create!(name: "QIYANA".downcase)
Tag.create!(name: "QUINN".downcase)
Tag.create!(name: "RAKAN".downcase)
Tag.create!(name: "RAMMUS".downcase)
Tag.create!(name: "REK'SAI".downcase)
Tag.create!(name: "RELL".downcase)
Tag.create!(name: "RENATA".downcase)
Tag.create!(name: "GLASC".downcase)
Tag.create!(name: "RENEKTON".downcase)
Tag.create!(name: "RENGAR".downcase)
Tag.create!(name: "RIVEN".downcase)
Tag.create!(name: "RUMBLE".downcase)
Tag.create!(name: "RYZE".downcase)
Tag.create!(name: "SAMIRA".downcase)
Tag.create!(name: "SEJUANI".downcase)
Tag.create!(name: "SENNA".downcase)
Tag.create!(name: "SERAPHINE".downcase)
Tag.create!(name: "SETT".downcase)
Tag.create!(name: "SHACO".downcase)
Tag.create!(name: "SHEN".downcase)
Tag.create!(name: "SHYVANA".downcase)
Tag.create!(name: "SINGED".downcase)
Tag.create!(name: "SION".downcase)
Tag.create!(name: "SIVIR".downcase)
Tag.create!(name: "SKARNER".downcase)
Tag.create!(name: "SONA".downcase)
Tag.create!(name: "SORAKA".downcase)
Tag.create!(name: "SWAIN".downcase)
Tag.create!(name: "SYLAS".downcase)
Tag.create!(name: "SYNDRA".downcase)
Tag.create!(name: "TAHM".downcase)
Tag.create!(name: "KENCH".downcase)
Tag.create!(name: "TALIYAH".downcase)
Tag.create!(name: "TALON".downcase)
Tag.create!(name: "TARIC".downcase)
Tag.create!(name: "TEEMO".downcase)
Tag.create!(name: "THRESH".downcase)
Tag.create!(name: "TRISTANA".downcase)
Tag.create!(name: "TRUNDLE".downcase)
Tag.create!(name: "TRYNDAMERE".downcase)
Tag.create!(name: "TWISTED FATE".downcase)
Tag.create!(name: "TWITCH".downcase)
Tag.create!(name: "UDYR".downcase)
Tag.create!(name: "URGOT".downcase)
Tag.create!(name: "VARUS".downcase)
Tag.create!(name: "VAYNE".downcase)
Tag.create!(name: "VEIGAR".downcase)
Tag.create!(name: "VEL'KOZ".downcase)
Tag.create!(name: "VEX".downcase)
Tag.create!(name: "VI".downcase)
Tag.create!(name: "VIEGO".downcase)
Tag.create!(name: "VIKTOR".downcase)
Tag.create!(name: "VLADIMIR".downcase)
Tag.create!(name: "VOLIBEAR".downcase)
Tag.create!(name: "WARWICK".downcase)
Tag.create!(name: "WUKONG".downcase)
Tag.create!(name: "XAYAH".downcase)
Tag.create!(name: "XERATH".downcase)
Tag.create!(name: "XIN ZHAO".downcase)
Tag.create!(name: "YASUO".downcase)
Tag.create!(name: "YONE".downcase)
Tag.create!(name: "YORICK".downcase)
Tag.create!(name: "YUUMI".downcase)
Tag.create!(name: "ZAC".downcase)
Tag.create!(name: "ZED".downcase)
Tag.create!(name: "ZERI".downcase)
Tag.create!(name: "ZIGGS".downcase)
Tag.create!(name: "ZILEAN".downcase)
Tag.create!(name: "ZOE".downcase)
Tag.create!(name: "ZYRA".downcase)